### ISSUE TITLE
Naming a concept represented by the `effect` 

### ISSUE THREAD

**Issue by dpraimeyuu** [christianalfoni/impact#137]
Hi @christianalfoni 😅 

I was wondering about the naming (and expressing ideas/concepts/abstractions):
```ts
effect(() => { // 👈 we are expressing something happening when some specific fact/event happens
        if (todos.remaining === 10) {
            notifications.add({ type: 'warning', text: "Oh oh, make sure you keep sane!" })
        }
    })
```

Should `effect` sound a little more "actionable"?
* `runEffect`?
* `reaction`?
* `reactWith`?
* `reactTo`?

Additionally, the signature of `effect` is:
```ts
type EffectHandler = () => void
type EffectCleanUp = () => void
type Effect = EffectHandler => EffectCleanUp 
```

I wonder if it makes sense to have similar to Overmind.js's `Reaction` - where dependencies are explicitly passed?

It helps readability and understanding what is actually "observed" 🤔 

So it would become:
```ts
effect([todos.remaining], (remainingTodos) => { // 👈 expressing observables explicitly
        if (remainingTodos === 10) {
            notifications.add({ type: 'warning', text: "Oh oh, make sure you keep sane!" })
        }
    })
```

Or even a super verbose version, enabling testing :-P 😅 
```ts
const createWarningAboutHyperProductivity = (notifications) => ([remainingTodos]) => {
	if (remainingTodos === 10) {
        notifications.add({ type: 'warning', text: "Oh oh, make sure you keep sane!" })
    }
}

const warningAboutHyperProductivity = createWarningAboutHyperProductivity(notifications)

react({ with: warningAboutHyperProductivity, to: [todos.remaining] })
```
Thanks for your inspiring work, as always 🙏

**Comment by christianalfoni** [comment]
Hi @dpraimeyuu 🤩 

Very good point on the naming convention there. So a bit of back story is that I was comparing the API of Solid JS and Preact Signals.

Preact Signals uses `effect`, `signal` etc. and Solid JS uses `createSignal` and `createEffect`. 

I was very torn here as I do value explicitness, but at the same time putting a `create` in front of every factory, like Solid JS,: `createContext`, `createGlobalStore`, `createStore` etc. makes it harder to differentiate the functions. You will be using these function a lot, also close to each other in the code. It just adds a bit of mental parsing overhead to differentiate them when they all start with `create`. I personally also like `reaction` more than things like `autorun` and `effect`, but we seem to be landing on a common terminology for reactivity now with Preact signals and Solid JS, so want to help settle the terminology 😄 

On your point of passing dependencies I do understand that this lack of explicitness takes away some understanding of how things work. I guess that is the cost of observability in general 🤔 That said, it also comes with a super power. That super power is dynamic observation. So for example:

```ts
effect(() => {
    // If we are on the remaining filter it will not observe the remaining todos, but as
    // soon as that changes it will
    if (todos.filter === 'remaining') {
      return
    }

    if (todos.remaining.length === 10) {
        notifications.add({ type: 'warning', text: "Oh oh, make sure you keep sane!" })
    }
})
```

With explicit dependencies this effect would always run when todos change, but you had no intention of running any logic:


```ts
// I always run because 
effect([todos.filter, todos.remaining], (filter, remainingTodos) => {
    if (filter === 'remaining') {
      return
    }

    if (remainingTodos.length === 10) {
        notifications.add({ type: 'warning', text: "Oh oh, make sure you keep sane!" })
    }
})
```

If I remember correctly we even added a `get` function to reactions to handle these dynamic scenarios 🤔 

Component reconciliation is really just an `effect` as well and there it becomes even more important as you avoid a lot of reconciliation by having this dynamic observation 😄 

I really appreciate the feedback and please do continue discussing or suggest emphasizing reasoning behind the API choices better in the docs 😄

**Comment by dpraimeyuu** [comment]
Firstly, thanks for your reply 🙏 

Insightful and informative for a mere mortal like me 😅 

When it comes to following a "community established-ish standard for naming", totally understandable.

`create*` suffix doesn't look that appealing to me. In my tiny example, I used it for emphasizing a higher-order function, but I wouldn't follow SolidJS convention there too.

`impact's` building blocks: `context`, `store`, and other friends, have a bit different semantics and meanings (at least in my mind): one could understand them not as "create store from" but "turn X into store" or "treat X as store", or "make X behave as store".

One could say - "Damian, why you are so nitpicky, those are just words" - everything starts with the names and concepts 😅 

When it comes to component reconciliation, now it makes sense to me to utilize dynamic observation in `effect` to have fine-grained reactivity 😊

But I still wonder about one simple scenario (I might misunderstand potential the consequences of such decision) - here's the implementation of `effect` in `impact`:
```ts
export function effect(cb: () => void) {
  let currentSubscriptionDisposer: (() => void) | undefined;

  const updater = () => {
    currentSubscriptionDisposer?.();
    const context = new ObserverContext();
    cb();
    context[Symbol.dispose]();
    currentSubscriptionDisposer = context.subscribe(updater);
  };

  updater();

  return cleanup(() => {
    currentSubscriptionDisposer?.();
  });
}
```

What will happen if we "just" pass signals (our "deps") to `cb`:
```ts
export function effect(deps: any[], cb: (deps: any[]) => void) { // 👈 added deps and make callback accept deps
  let currentSubscriptionDisposer: (() => void) | undefined;

  const updater = () => {
    currentSubscriptionDisposer?.();
    const context = new ObserverContext();
    cb(deps); // 👈 passing deps up to callback
    context[Symbol.dispose]();
    currentSubscriptionDisposer = context.subscribe(updater);
  };

  updater();

  return cleanup(() => {
    currentSubscriptionDisposer?.();
  });
}
```

Would it lose "dynamic observation" attribute? 🤔

**Comment by christianalfoni** [comment]
Hi again 😄 

Yeah, I agree simplifying APIs like this creates ambiguity. Like `store` does not even state that it is a state store, let alone creating one 😂 It could be like "storing a value" if you think of it as a verb.

You could also do things like:

```ts
import { Signal, Store } from 'impact-app'

const store = Store.from({
  count: 0
})

const count = Signal.from(0)
```

That helps emphasize what kind of instance you are creating as well... though it is very "class based" and does not really fit that well with the paradigm of React I am thinking 🤔 

We used to have `observe` instead of `effect`, which I think fits really well, cause your are literarily observing the execution of the callback. Though it was removed cause we had that related to components as well... and then there is the "Help settle on terms" argument.

So technically the more correct thing would be:

`createSignalStore` and `createObserverContext`. 

Also the history of JavaScript affects this... like... who builds a library behind a `$` 😂, we do like our simplification.

About the `deps` thing. It depends. So:

```ts
// This would not work, cause you access the count outside the scope of the effect callback
effect([countSignal.value], (count) => {

})

// So you would have to ensure you pass an actual signal
effect([countSignal], (count) => {

})

// But this becomes a problem with stores, cause they always give you the value
effect([store.count], (count) => {

})
```

Then it depends on where the deps signals are accessed related to the observer context created inside the effect 😄 With your example you would still get dynamic observation as the callback is called after the creation of the observer context, and before its disposal. But yeah, it would really need to iterate the deps array and call `dep.value` to actually access the signal and make it part of the observer context:

```ts
export function effect(signalDeps: any[], cb: (...signalDeps: any[]) => void) { // 👈 added deps and make callback accept deps
  let currentSubscriptionDisposer: (() => void) | undefined;

  const updater = () => {
    currentSubscriptionDisposer?.();
    const context = new ObserverContext();
    cb(...signalDeps.map(dep => dep.value)); // 👈 passing deps up to callback
    context[Symbol.dispose]();
    currentSubscriptionDisposer = context.subscribe(updater);
  };

  updater();

  return cleanup(() => {
    currentSubscriptionDisposer?.();
  });
}
```

But yeah, as shown above it is not clear exactly what to pass in the deps array and also stores would not work with them as when accessing `store.count` you access the underlying `count.value` of the signal.

I am going to reflect more on the naming of the API. It does itch a lot that it is not obvious in isolation what the APIs actually do 😄 Please continue and add more perspectives and suggestions! :D

**Comment by dpraimeyuu** [comment]
Thanks for the elaborating with examples!

With Overmind, the primitive was "proxy state tree" so the concept of `reaction` was able to *react* surgically to mutations. 

Here, the primitive is a signal which has different mechanics! (my current understanding :sweat_smile:)

Still, in the first version one might not have "perfect" API (whatever it means) - in the worst-case scenario, I can write my own "language-capturing primitive":
```ts
// somewhere in `@/impact-app/extensions`
export const react = ({to, with}: ReactionParams) => effect(with(to)) 

```
```ts
// in another file
import { react } from "@/impact-app/extensions"
const warningAboutBeingTooProductive = ([todosFilter, remainingTodos]) => () => {
    if (todosFilter === 'remaining') {
      return
    }

    if (remainingTodos.length === 10) {
        notifications.add({ type: 'warning', text: "Oh oh, make sure you keep sane!" })
    }
}

//...
react({ to: [todos.filter, todos.remaining], with: warningAboutBeingTooProductive })
```

No magic there, just function composition. Hence, I believe it should work without a hassle :sweat_smile: (but still: "talking is cheap, show me the code" :rofl: )

Regarding this:
> You could also do things like:
>```ts
> import { Signal, Store } from "impact-app"
>
>const store = Store.from({
> count: 0
>})
>
>const count = Signal.from(0)
>```
>That helps emphasize what kind of instance you are creating as well... **though it is very "class based" and does not really
> fit that well with the paradigm of React I am thinking** 🤔

It might be a class, it might be a module - depending on whom we ask :sweat_smile: 

In functional-first languages like F# or Elixir, it's pretty common to "require qualified access" to module's functions (either by the compiler or by convention) so that `from` is a public function available "in the module" and **must** be preceded with module name.

`store`, `context`, `signal` look good enough to start and no one probably would ever think of "why the hell there's no `Signal.from` API?!" :sweat_smile:
