### ISSUE TITLE
Some user feedback

### ISSUE THREAD

**Issue by fmal** [christianalfoni/impact#171]
Hi @christianalfoni,

thanks so much for open sourcing another fantastic tool. I've been long time user of your state management solutions and Impact seems like a great evolution. I really like the possibilities it offers with just a bunch of well-thought primitives. Taking advantage of component tree scoping while avoiding the pitfalls of sharing state tied to the reconciliation loop via context is so interesting. I've been following your progress on Impact and i'm pumped to use it in a new project. Please keep sharing more thoughts and resources ❤️ 

Some questions are popping in my head after couple of days of trying out Impact:

1. What is the actual difference between:
 
    ```js
    const appContext = context(() => {
        const message = signal('Hello World')
        const shoutingMessage = derived(() => message.value + '!!!')

        return {
           get message() {
               return message.value
           },
           get shoutingMessage() {
               return shoutingMessage.value
           }
       }
    })
    ```

    and 

   ```js
   const appContext = context(() => {
       const message = signal('Hello World')
   
       return {
           get message() {
               return message.value
           },
           get shoutingMessage() {
               return shoutingMessage.value + '!!!';
           }
       }
   })
   ```

   I think the examples above are functionally equivalent and it's also possible to track promise signals inside `get`.             
   What is the advantage of using `derived` and why does it need it's own `ObserverContext`?
   Would it be OK to use regular getters for simple derive scenarios? 

2. Docs mention that `Signals are expected to be treated as immutable values`, so i guess it won't work to wrap some complex array of objects in a single signal, modify this data "in place" and then reassign the signal value? To mutate some particular object and notify the components you would have to pay the cost of cloning everything. Would it be recommended to wrap each object in it's own signal to allow more granular mutations? I'm curious what is your approach.

Thank you!

**Comment by christianalfoni** [comment]
Hi @fmal and thanks so much for the encouraging feedback! ❤️ 

1. So you are right that they are practically the same. They both evaluate the value when consuming the value. The difference is that `derived` will cache the value. So basically it observes the signals consumed within it and if any of them change it flags the derived as dirty. When someone consumes the derived value it will run the callback, but unless any of the signals within change it will use the already "calculcated" value 😄 Does that make sense? I can make this more in the docs. Do you think it is valuable information already where the derived is first mentioned or enough to emphasize in the `signals` docs?
2. This is where **Mobx** really shines. You do not have to consider this stuff, but at the cost of using Proxies and diverging from Reacts immutability. So I was actually considering using Mobx for the observability, but it diverges too much from Reacts principles IMO and there where things I wanted to do, like observable promises, that signals become the thing. So in my experience I would rather lean on tools like [immer](https://immerjs.github.io/immer/) to still use mutation API, but do the right "reference updates" AKA "immutability". Also something to notice is that `data` and `signals` are different things. There is nothing wrong with creating a context around every item in a list, if the data of that item is complex. You can see an example of that here: https://github.com/christianalfoni/family-scrum-v2/blob/main/src/AppContext/PlanNextWeek/WeekTodosContext/WeekTodos.tsx#L14. It renders a context for every item, cause the item is really complex. That allows you to take some complex data object into the context and create more granular signals from it:

```ts
function MyItemContext({ data }) {
  const title = signal(data.title)
  const description = signal(data.description)

  return {
    get title() {
      return title.value
    },
    get description() {
      return decription.value
    }
  }
}
```

So in my experience the complexity of data is strongly correlated with the complexity of its state management, meaning you are way more likely to have a signal for the list of complex data items, but then each data item is passed into its own context (Like the linked example) where you choose what part of that data needs to be their own signals 😄 Does that make sense? I think this would be a good `advanced` section in the docs. Managing complex data, what you think?

**Comment by fmal** [comment]
Thanks so much for the thorough explanation and additional context ❤️ 

1. Now i better understand the value of `derived` 👍  I think it would be great to mention in the docs that the returned value is actually memoized unless the underlying signals change! It wasn't obvious at all for me, until you mentioned it and by looking again at the implementation :)
2. Good points :) MobX or **Overmind** that also uses proxies to track mutations 😃 Yeah, observable promises are great feature of Impact, i see why you did that. One particular case i was wondering about is when you need to fetch a large piece of data (say 30000 of objects in a collection) on app initialisation and later on some parts of it can be constantly mutated by different sources like user events or subscription, but you still want to observe the data in its "entirety" (creating a context around each row/item wouldn't really help in that case). Updates coming through subscription could be granular, but you would need to subscribe at a context level where you store the whole collection in a signal and overwrite it's value with new immutable data produced with help of immer as you mentioned. Whereas with tool like Overmind you don't really have to be concerned with what data needs to be wrapped as observable, you can efficiently mutate deeply nested state parts without paying the cost of cloning the data. I guess it depends on the complexity of data as you said and low-level `signal` primitive might be much harder to work with in these instances than a proxy state tracking approach (where you get granular observability out of the box). That's why i think Overmind approach is still quite relevant for complex state management, even though i love the simplicity, scoping and colocation via context, observable promises etc in Impact.

   Anyway, something like `advanced` section in the docs would be a great addition, i can see the stuff you mentioned in the answer like using `immer` to mutate complex data or wrapping items in their own context would be quite helpful. 

    By the way is immutability a requirement for impact? I guess here is the code that enforces it https://github.com/christianalfoni/impact/blob/main/impact-app/src/signal.ts#L171, but wouldn't notify after mutation still trigger observers?

**Comment by christianalfoni** [comment]
Hi again @fmal 😄 

Ah, yes, I see what you mean and I totally agree. It definitely removes a mental load if you can just define whatever observables you want and you do not have to think about the nested observability, which I do love about Mobx and Overmind as well 👍 😄 

That said, signals are very flexible, so in this situation what you could do is:

```tsx
function AppContext() {
  // In this example we store the items in an array, where each item is a signal
  const items = [signal(itemA), signal(itemB), signal(itemC)]

  // Then we separately have a signal responsible for what items to display in our list,
  // you have full freedom here on the length of the list, sorting type, just insert a new
  // item if you add one to a filtered list that does not necessary match the current
  // filter etc.
  const itemsToDisplay = signal([0, 1, 2])

  // Start some subscription that updates the items

  return {
    getItemByIndex(index) {
      return items[index].value
    },
    get itemsToDisplay() {
      return itemsToDisplay.value
    }
  }
}

const useAppContext = context(AppContext)

function List() {
  const { itemsToDisplay } = useAppContext()

  return <ul>{itemsToDisplay.map((index) => <Item key={index} index={index} />}</ul>
}

function Item({ index }) {
  const { getItemByIndex } = useAppContext()
  const item = getItemByIndex(index)
  
}
```

Or you could structure the items as a map and use keys instead of indexes:

```tsx
function AppContext() {
  const itemsToDisplay = signal(['123', '456', '789'])
  const items = {
    123: signal(itemA),
    456: signal(itemB),
    789: signal(itemC)
  }

  // Some subscription updating items

  return {
    getItemById(id) {
      return items[id].value
    },
    get itemsToDisplay() {
      return itemsToDisplay.value
    }
  }
}

const useAppContext = context(AppContext)

function List() {
  const { itemsToDisplay } = useAppContext()

  return <ul>{itemsToDisplay.map((id) => <Item key={id} id={id} />}</ul>
}

function Item({ id }) {
  const { getItemById } = useAppContext()
  const item = getItemById(id)
  
}
```

So this is the same, only using IDs and a map. 

The great thing here is that you consciously control when the list should render, with full freedom on the contents of the list and each item will reconcile individually as you consume them in each Item component. Does that make sense?

It is of course less mental load to just have an array and start updating it and consuming it in components, but in that case you would probably:

```tsx
function List() {
  const { items } = useAppContext()

  return <ul>{items.map((item) => <Item key={id} item={item} />}</ul>
}
```

And now you have the mental overload of understanding why this passing of `item` does NOT cause a reconciliation in the `Item` component, as it will never change reference due to mutation... unlike all other object props passing in React 😄 

Does that make sense?

**Comment by christianalfoni** [comment]
I just added this 😄 : https://github.com/christianalfoni/impact/blob/main/docs/02_lists.md

**Comment by fmal** [comment]
@christianalfoni thank you, i think this guide is a very valuable addition to the docs! It helped me better settle things in my head 👍  What you shown makes total sense and demonstrates the flexibility of the signal primitive. 

To better illustrate the flexibility you could even store the promise of fetching initial data in a `signal` and build the `items` lookup by id with help of `derived` when that promise is fulfilled. This is also where the caching/memoization of `derived` shines 😉 

So yeah i guess there is always a way to be as granular as you want with some additional effort using `signal` but that is just a consequence of having small, flexible primitives.

Thanks for the good discussion and examples, i'm very happy with the outcome and closing the "issue".

Please keep up sharing as you iterate on this stuff, it's super interesting to follow along <3
